# Generated by Django 6.0.6 on 2026-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_count', models.IntegerField(default=0)),
                ('low_stock_count', models.IntegerField(default=0)),
                ('reservations_count', models.IntegerField(default=0)),
                ('debtors_count', models.IntegerField(default=0)),
                ('top_products_summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
