# Generated by Django 6.0.6 on 2026-06-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('CONFIRMED', 'Tasdiqlangan'), ('ARRIVED', 'Keldi (Band)'), ('COMPLETED', 'Yakunlangan'), ('CANCELLED', 'Bekor qilingan'), ('NO_SHOW', 'Kelmadi')], default='PENDING', max_length=50),
        ),
    ]
