# Generated by Django 6.0.6 on 2026-06-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='payment_type',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('uzcard', 'Uzcard'), ('humo', 'Humo'), ('click', 'Click'), ('payme', 'Payme'), ('transfer', "Bank O'tkazmasi")], default='naqd', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('uzcard', 'Uzcard'), ('humo', 'Humo'), ('click', 'Click'), ('payme', 'Payme'), ('transfer', "Bank O'tkazmasi")], default='naqd', max_length=50),
        ),
    ]
