# Generated by Django 6.0.6 on 2026-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_debtpayment_payment_type_expense_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='OPEN', max_length=20),
        ),
    ]
