# Generated by Django 6.0.6 on 2026-06-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('click_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payme_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('naqd', 'Naqd'), ('uzcard', 'Uzcard'), ('humo', 'Humo'), ('click', 'Click'), ('payme', 'Payme'), ('transfer', "Bank O'tkazmasi")], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
        ),
    ]
