# Generated by Django 6.0.6 on 2026-06-06 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_dailyreport_salepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.CharField(default='Kassir', max_length=100)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.shift'),
        ),
    ]
