# Generated by Django 6.0.6 on 2026-06-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_shift_sale_status_sale_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('AVAILABLE', "Bo'sh"), ('OCCUPIED', 'Band'), ('RESERVED', 'Bron qilingan')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.table'),
        ),
    ]
