# Generated by Django 6.0.6 on 2026-06-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_saleitem_menu_item_alter_saleitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='cogs_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shift',
            name='cogs_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
