# Generated by Django 6.0.6 on 2026-06-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Ofitsiant', 'Ofitsiant'), ('Hostes', 'Hostes'), ('Povar', 'Povar'), ('Posudamoyka', 'Posudamoyka'), ('Uborkachi', 'Uborkachi'), ('Menejer', 'Menejer'), ('Dostavshik', 'Dostavshik'), ('Kassir', 'Kassir'), ('Barmen', 'Barmen')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
        ),
    ]
