# Generated by Django 6.0.6 on 2026-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeadvance_employeefine'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvance',
            name='advance_type',
            field=models.CharField(choices=[('avans', 'Avans'), ('maosh', 'Maosh')], default='avans', max_length=20),
        ),
    ]
